Py3
halostatue/rubypython pull request #3
Opened 2015-02-10 02:25 UTC by kitech

hi,
I try to let rubypython support python3, and for my little program it works fine.

But i don't known how merge to master and make it compatitate with both python2 and python3.

suggest me  if this pull request need more improvement.

Thanks.

2015-02-10 20:46 UTC, halostatue commented
Thank you. I will look at this when I have time. It may get more response if it is put on the parent repository (https://bitbucket.org/raineszm/rubypython/src)—which will require doing things in Mercurial.

2017-06-22 03:16 UTC, peter-wangxu requested changes
Hi @kitech Can you add some python3 code under `python_helpers` and test it via ruby?

Thanks
Peter

2017-06-22 03:16 UTC, peter-wangxu commented on lib/rubypython/interpreter.rb
> +      #warn "The python interpreter is python 3, switching to python2"
Please remove the logic `if` if it's unnecessary.

2017-08-02 06:37 UTC, afeldman commented
I forked this project and I make a python3 change for linux.

2017-08-02 07:24 UTC, peter-wangxu commented
@afeldman feel free to send separate PR once you complete the testing for you change.

2017-08-10 00:43 UTC, afeldman commented
Can I open a new branch for python3?

2017-08-10 04:16 UTC, peter-wangxu commented
do you mean separating the python3 support from current python2？

2017-10-07 01:35 UTC, afeldman commented
yes. I do not support python2 in that project. I try to switch compliantly to python3. It is a lot of work to make the project python2 and python3 compatible, because of the change in the c datatypes

2017-10-07 11:49 UTC, peter-wangxu commented
Looks fine. it's the first step to support python3 based on current code base.

Please let me know if you need some extra support from my side.
Kindly send the PR with test code. cannot help reviewing your changes.

2025-10-22 00:16 UTC, closed without merging